from app.document_types.schemas import document_type


ACCESSORY_TYPES = [
    document_type("DECLARACAO_DESIMPEDIMENTO", "Declaração de Desimpedimento", "Declaração de desimpedimento", "ACCESSORY", "Documento acessório", "Declaração de inexistência de impedimento para administração.", "Acompanhar atos com administrador ou diretor.", ["declarante", "cargo", "empresa"], ["local_data"], ["documento_declarante"], ["validar_declarante", "validar_cargo"], ["cargo_divergente", "qualificacao_incompleta"]),
    document_type("DECLARACAO_ENQUADRAMENTO_ME_EPP", "Declaração de Enquadramento ME/EPP", "Declaração de enquadramento ME/EPP", "ACCESSORY", "Documento acessório", "Declaração de enquadramento como ME ou EPP.", "Registrar condição empresarial quando aplicável.", ["empresa", "porte", "representante"], ["receita_bruta"], ["documentos_empresa"], ["validar_porte", "validar_representante"], ["porte_incorreto", "representante_incoerente"]),
    document_type("REENQUADRAMENTO_ME_EPP", "Reenquadramento ME/EPP", "Reenquadramento ME/EPP", "ACCESSORY", "Documento acessório", "Ato de reenquadramento de porte empresarial.", "Atualizar porte empresarial.", ["empresa", "porte_atual", "novo_porte", "representante"], ["motivo"], ["documentos_empresa"], ["validar_porte"], ["porte_divergente", "motivo_ausente"]),
    document_type("DESENQUADRAMENTO_ME_EPP", "Desenquadramento ME/EPP", "Desenquadramento ME/EPP", "ACCESSORY", "Documento acessório", "Ato de desenquadramento de ME/EPP.", "Formalizar alteração de porte.", ["empresa", "porte_atual", "motivo", "representante"], ["data_efeito"], ["documentos_empresa"], ["validar_motivo", "validar_data_efeito"], ["motivo_incompleto", "data_inconsistente"]),
    document_type("PROCURACAO", "Procuração", "Procuração", "ACCESSORY", "Documento acessório", "Instrumento de mandato para representação.", "Autorizar representante para atos específicos.", ["outorgante", "outorgado", "poderes"], ["prazo", "substabelecimento"], ["documentos_partes"], ["validar_poderes", "validar_partes"], ["poderes_ambíguos", "qualificacao_incompleta", "prazo_ausente"]),
    document_type("TERMO_DE_POSSE", "Termo de Posse", "Termo de posse", "ACCESSORY", "Documento acessório", "Termo de posse de administrador ou diretor.", "Formalizar posse em cargo societário.", ["empossado", "cargo", "empresa", "mandato"], ["declaracao_desimpedimento"], ["documentos_empossado"], ["validar_cargo", "validar_mandato"], ["mandato_divergente", "cargo_incoerente"]),
    document_type("CARTA_RENUNCIA", "Carta de Renúncia", "Carta de renúncia", "ACCESSORY", "Documento acessório", "Carta de renúncia de cargo societário.", "Formalizar renúncia para registro ou ciência.", ["renunciante", "cargo", "empresa", "data_renuncia"], ["motivo"], ["documento_renunciante"], ["validar_cargo", "validar_data"], ["data_inconsistente", "cargo_divergente"]),
    document_type("RECIBO_TRANSFERENCIA_QUOTAS", "Recibo de Transferência de Quotas", "Recibo de transferência de quotas", "ACCESSORY", "Documento acessório", "Recibo de cessão ou transferência de quotas.", "Comprovar operação de transferência de quotas.", ["cedente", "cessionario", "quotas", "valor"], ["forma_pagamento"], ["documentos_partes", "contrato_social"], ["validar_quotas", "validar_valor"], ["quotas_divergentes", "valor_ausente"]),
    document_type("LISTA_PRESENCA", "Lista de Presença", "Lista de presença", "ACCESSORY", "Documento acessório", "Lista de presença de assembleia ou reunião.", "Comprovar presença de sócios ou acionistas.", ["empresa", "data", "participantes"], ["percentuais", "assinaturas"], ["documentos_participantes"], ["validar_participantes", "validar_percentuais"], ["participante_ausente", "percentual_divergente"]),
    document_type("BOLETIM_SUBSCRICAO", "Boletim de Subscrição", "Boletim de subscrição", "ACCESSORY", "Documento acessório", "Boletim para subscrição de ações ou quotas.", "Registrar subscrição em aumento de capital.", ["subscritor", "quantidade", "valor", "empresa"], ["forma_integralizacao"], ["documentos_subscritor"], ["validar_subscricao", "validar_valor"], ["quantidade_divergente", "integralizacao_ausente"]),
]
