from app.document_types.schemas import document_type


EMPRESARIO_INDIVIDUAL_TYPES = [
    document_type("CONSTITUICAO_EMPRESARIO_INDIVIDUAL", "Constituição de Empresário Individual", "Constituição de empresário individual", "EI_SLU", "Empresário Individual / SLU", "Ato de constituição de empresário individual.", "Formalizar inscrição empresarial individual.", ["empresario", "endereco", "objeto_social", "capital"], ["nome_fantasia"], ["documentos_empresario", "viabilidade", "dbe"], ["validar_qualificacao", "validar_objeto"], ["qualificacao_incompleta", "objeto_inadequado", "endereco_incompleto"]),
    document_type("ALTERACAO_EMPRESARIO_INDIVIDUAL", "Alteração de Empresário Individual", "Alteração de empresário individual", "EI_SLU", "Empresário Individual / SLU", "Alteração de dados cadastrais de empresário individual.", "Atualizar dados do empresário individual.", ["empresario", "dados_alterados", "novo_texto"], ["endereco", "objeto_social", "capital"], ["ato_atual", "documentos_empresario"], ["validar_dados_alterados"], ["dados_divergentes", "qualificacao_desatualizada"]),
    document_type("EXTINCAO_EMPRESARIO_INDIVIDUAL", "Extinção de Empresário Individual", "Extinção de empresário individual", "EI_SLU", "Empresário Individual / SLU", "Ato de extinção de empresário individual.", "Formalizar encerramento do registro.", ["empresario", "motivo_extincao", "data_encerramento"], ["declaracoes"], ["ato_atual", "comprovantes_baixa"], ["validar_responsabilidade", "validar_data"], ["pendencias_cadastrais", "data_inconsistente"]),
    document_type("CONSTITUICAO_SLU", "Constituição de Sociedade Limitada Unipessoal", "Constituição de SLU", "EI_SLU", "Empresário Individual / SLU", "Contrato de constituição de sociedade limitada unipessoal.", "Criar SLU para registro na Junta Comercial.", ["razao_social", "socio_unico", "endereco_sede", "objeto_social", "capital_social", "administrador"], ["nome_fantasia", "pro_labore", "foro"], ["documentos_socio", "viabilidade", "dbe"], ["validar_socio_unico", "validar_capital", "validar_administrador"], ["qualificacao_incompleta", "capital_inconsistente", "administrador_incoerente"]),
    document_type("ALTERACAO_SLU", "Alteração de Sociedade Limitada Unipessoal", "Alteração de SLU", "EI_SLU", "Empresário Individual / SLU", "Alteração contratual de SLU.", "Atualizar dados da sociedade limitada unipessoal.", ["razao_social", "socio_unico", "dados_alterados"], ["endereco_sede", "objeto_social", "capital_social", "administrador"], ["contrato_atual", "viabilidade", "dbe"], ["validar_socio_unico", "validar_alteracoes"], ["dados_divergentes", "clausulas_conflitantes"]),
    document_type("EXTINCAO_SLU", "Extinção de Sociedade Limitada Unipessoal", "Extinção de SLU", "EI_SLU", "Empresário Individual / SLU", "Distrato ou ato de extinção de SLU.", "Formalizar encerramento da sociedade limitada unipessoal.", ["razao_social", "socio_unico", "motivo_extincao", "responsavel_guarda_livros"], ["balanco", "declaracoes"], ["contrato_atual", "balanco_encerramento"], ["validar_responsavel", "validar_extincao"], ["responsavel_ausente", "pendencias_fiscais", "data_inconsistente"]),
]
