from app.document_types.schemas import document_type


LTDA_TYPES = [
    document_type(
        code="CONSTITUICAO_LTDA",
        label="Constituição de Sociedade Limitada",
        user_label="Constituição de LTDA",
        group="LTDA",
        user_group="Contrato Social / LTDA",
        description="Contrato social inicial para constituição de sociedade limitada.",
        purpose="Criar contrato social para registro na Junta Comercial.",
        required_fields=["razao_social", "endereco_sede", "objeto_social", "capital_social", "socios", "administradores"],
        optional_fields=["nome_fantasia", "pro_labore", "clausulas_especiais", "foro", "testemunhas", "advogado"],
        supporting_documents=["documentos_socios", "comprovante_endereco", "viabilidade", "dbe"],
        validation_rules=["validar_soma_quotas", "validar_percentuais", "validar_qualificacao_socios", "validar_administrador"],
        risk_points=["qualificacao_incompleta", "capital_inconsistente", "objeto_social_inadequado", "administrador_incoerente"],
        notes="Primeiro tipo recomendado para geração futura.",
    ),
    document_type(
        "ALTERACAO_ENDERECO_LTDA",
        "Alteração Contratual de Endereço de LTDA",
        "Alteração de endereço",
        "LTDA",
        "Alteração Contratual",
        "Alteração contratual para mudança de sede de sociedade limitada.",
        "Atualizar endereço da sede perante Junta Comercial e cadastros correlatos.",
        ["razao_social", "endereco_atual", "novo_endereco", "socios", "administradores"],
        ["viabilidade", "dbe", "consolidacao"],
        ["comprovante_endereco", "viabilidade", "dbe"],
        ["validar_endereco_novo", "validar_coexistencia_endereco_antigo_novo"],
        ["endereco_incompleto", "comarca_incorreta", "dbe_divergente"],
    ),
    document_type(
        "ALTERACAO_OBJETO_LTDA",
        "Alteração Contratual de Objeto Social de LTDA",
        "Alteração de objeto social",
        "LTDA",
        "Alteração Contratual",
        "Alteração contratual para inclusão, exclusão ou ajuste de objeto social.",
        "Adequar atividades da empresa no contrato social.",
        ["razao_social", "objeto_atual", "novo_objeto", "socios"],
        ["cnaes", "viabilidade", "dbe"],
        ["viabilidade", "dbe", "consulta_cnae"],
        ["validar_objeto_social", "validar_cnaes"],
        ["objeto_amplo", "objeto_incompatível", "cnae_divergente"],
    ),
    document_type(
        "ALTERACAO_CAPITAL_LTDA",
        "Alteração Contratual de Capital Social de LTDA",
        "Alteração de capital",
        "LTDA",
        "Alteração Contratual",
        "Alteração contratual para aumento, redução ou redistribuição de capital.",
        "Registrar nova composição do capital social e quotas.",
        ["razao_social", "capital_atual", "novo_capital", "socios", "quotas"],
        ["forma_integralizacao", "prazo_integralizacao"],
        ["quadro_societario", "comprovantes_integralizacao"],
        ["validar_soma_quotas", "validar_percentuais", "validar_integralizacao"],
        ["capital_inconsistente", "percentuais_divergentes", "integralizacao_ausente"],
    ),
    document_type(
        "ALTERACAO_SOCIOS_LTDA",
        "Alteração Contratual de Sócios de LTDA",
        "Alteração de sócios",
        "LTDA",
        "Alteração Contratual",
        "Entrada, saída ou transferência de quotas entre sócios.",
        "Atualizar quadro societário e distribuição de quotas.",
        ["razao_social", "socios_atuais", "socios_entrantes", "socios_retirantes", "quotas"],
        ["cessao_quotas", "preco_transferencia", "anuencia_conjuge"],
        ["documentos_socios", "contrato_atual", "recibo_transferencia"],
        ["validar_qualificacao_socios", "validar_soma_quotas", "validar_cessao"],
        ["qualificacao_incompleta", "quotas_inconsistentes", "cessao_ambigua"],
    ),
    document_type(
        "ALTERACAO_ADMINISTRACAO_LTDA",
        "Alteração Contratual de Administração de LTDA",
        "Alteração de administração",
        "LTDA",
        "Alteração Contratual",
        "Alteração de administrador, poderes ou forma de administração.",
        "Atualizar administração da sociedade limitada.",
        ["razao_social", "administrador_atual", "novo_administrador", "socios"],
        ["pro_labore", "poderes", "prazo"],
        ["documentos_administrador", "contrato_atual"],
        ["validar_administrador", "validar_desimpedimento"],
        ["genero_administrador", "poderes_ambíguos", "desimpedimento_ausente"],
    ),
    document_type(
        "ALTERACAO_NOME_EMPRESARIAL_LTDA",
        "Alteração Contratual de Nome Empresarial de LTDA",
        "Alteração de nome empresarial",
        "LTDA",
        "Alteração Contratual",
        "Alteração da denominação ou razão social da sociedade limitada.",
        "Registrar novo nome empresarial.",
        ["nome_atual", "novo_nome", "socios"],
        ["nome_fantasia", "viabilidade"],
        ["viabilidade", "dbe"],
        ["validar_nome_empresarial", "validar_viabilidade"],
        ["nome_divergente", "viabilidade_pendente", "dbe_divergente"],
    ),
    document_type(
        "CONSOLIDACAO_CONTRATO_SOCIAL_LTDA",
        "Consolidação de Contrato Social de LTDA",
        "Consolidação contratual",
        "LTDA",
        "Contrato Social / LTDA",
        "Consolidação integral do contrato social após alterações.",
        "Organizar o contrato social vigente em texto único.",
        ["razao_social", "contrato_atual", "alteracoes", "socios"],
        ["clausulas_especiais", "foro"],
        ["contrato_atual", "alteracoes_anteriores"],
        ["validar_coerencia_clausulas", "validar_numeracao"],
        ["clausulas_conflitantes", "historico_incompleto", "numeracao_inconsistente"],
    ),
    document_type(
        "DISTRATO_SOCIAL_LTDA",
        "Distrato Social de LTDA",
        "Distrato social",
        "LTDA",
        "Contrato Social / LTDA",
        "Documento para dissolução e extinção de sociedade limitada.",
        "Formalizar encerramento da sociedade.",
        ["razao_social", "socios", "motivo_distrato", "responsavel_guarda_livros"],
        ["balanco", "partilha", "declaracoes"],
        ["contrato_atual", "balanco_encerramento"],
        ["validar_responsavel", "validar_partilha"],
        ["responsavel_ausente", "partilha_inconsistente", "pendencias_fiscais"],
    ),
    document_type(
        "TRANSFORMACAO_TIPO_JURIDICO",
        "Transformação de Tipo Jurídico",
        "Transformação de tipo jurídico",
        "LTDA",
        "Alteração Contratual",
        "Ato para transformação de natureza jurídica empresarial.",
        "Formalizar mudança de tipo jurídico perante a Junta Comercial.",
        ["tipo_atual", "novo_tipo", "razao_social", "socios"],
        ["estatuto_ou_contrato_consolidado", "deliberacoes"],
        ["ato_atual", "documentos_socios"],
        ["validar_tipo_juridico", "validar_quorum", "validar_texto_consolidado"],
        ["quorum_insuficiente", "texto_consolidado_incompatível", "cadastro_divergente"],
    ),
]
