from app.document_types.schemas import document_type


SA_TYPES = [
    document_type("ATA_AGE", "Ata de Assembleia Geral Extraordinária", "Ata AGE", "SA", "Ata / Assembleia", "Ata de deliberações extraordinárias de sociedade anônima.", "Registrar deliberações extraordinárias.", ["companhia", "data_hora_local", "presenca", "ordem_do_dia", "deliberacoes"], ["mesa", "convocacao", "publicacoes"], ["estatuto_social", "livro_presenca"], ["validar_quorum", "validar_ordem_do_dia", "validar_deliberacoes"], ["quorum_incompleto", "deliberacao_ambigua", "estatuto_incompatível"]),
    document_type("ATA_AGO", "Ata de Assembleia Geral Ordinária", "Ata AGO", "SA", "Ata / Assembleia", "Ata ordinária para contas, administração e destinações legais.", "Registrar deliberações ordinárias anuais.", ["companhia", "data_hora_local", "presenca", "contas_administracao", "deliberacoes"], ["mesa", "publicacoes"], ["demonstracoes_financeiras", "livro_presenca"], ["validar_prazo_ago", "validar_contas", "validar_quorum"], ["prazo_incorreto", "contas_incompletas", "assinaturas_ausentes"]),
    document_type("ATA_AGOE", "Ata de Assembleia Geral Ordinária e Extraordinária", "Ata AGO/AGE conjunta", "SA", "Ata / Assembleia", "Ata conjunta para deliberações ordinárias e extraordinárias.", "Registrar matérias ordinárias e extraordinárias no mesmo ato.", ["companhia", "data_hora_local", "presenca", "ordem_do_dia", "deliberacoes"], ["mesa", "publicacoes"], ["estatuto_social", "demonstracoes_financeiras"], ["validar_separacao_materias", "validar_quorum"], ["materias_confundidas", "quorum_divergente", "deliberacao_incompleta"]),
    document_type("ESTATUTO_SOCIAL", "Estatuto Social", "Estatuto social", "SA", "Estatuto Social", "Estatuto de sociedade anônima.", "Definir regras estruturais da companhia.", ["companhia", "sede", "objeto_social", "capital_social", "acoes", "administracao"], ["conselho", "diretoria", "assembleias"], ["boletim_subscricao", "documentos_acionistas"], ["validar_capital_acoes", "validar_administracao"], ["capital_inconsistente", "poderes_excessivos", "artigos_conflitantes"]),
    document_type("ESTATUTO_SOCIAL_CONSOLIDADO", "Estatuto Social Consolidado", "Estatuto social consolidado", "SA", "Estatuto Social", "Texto consolidado do estatuto após alterações.", "Consolidar regras estatutárias vigentes.", ["companhia", "estatuto_atual", "alteracoes_aprovadas"], ["diretoria", "capital_social"], ["atas_anteriores", "estatuto_atual"], ["validar_coerencia_ata_estatuto", "validar_numeracao_artigos"], ["artigos_repetidos", "alteracao_nao_refletida", "poderes_divergentes"]),
    document_type("ALTERACAO_ENDERECO_SA", "Alteração de Endereço de S/A", "Alteração de endereço de S/A", "SA", "Ata / Assembleia", "Ato societário para alteração de sede de sociedade anônima.", "Atualizar sede e estatuto, quando aplicável.", ["companhia", "endereco_atual", "novo_endereco", "deliberacoes"], ["estatuto_consolidado"], ["viabilidade", "estatuto_social"], ["validar_endereco_novo", "validar_reflexo_estatuto"], ["endereco_antigo_novo_confundidos", "estatuto_nao_consolidado"]),
    document_type("ALTERACAO_DIRETORIA_SA", "Alteração de Diretoria de S/A", "Alteração de diretoria", "SA", "Ata / Assembleia", "Eleição, renúncia ou substituição de diretores.", "Atualizar composição da diretoria.", ["companhia", "diretores_atuais", "novos_diretores", "mandato"], ["termo_posse", "declaracao_desimpedimento"], ["documentos_diretores", "estatuto_social"], ["validar_mandato", "validar_desimpedimento"], ["mandato_incompatível", "qualificacao_incompleta", "cargo_incoerente"]),
    document_type("ALTERACAO_ESTATUTO_SA", "Alteração de Estatuto Social", "Alteração de estatuto", "SA", "Estatuto Social", "Alteração de artigos estatutários.", "Atualizar cláusulas estatutárias deliberadas.", ["companhia", "artigos_atuais", "nova_redacao", "deliberacoes"], ["estatuto_consolidado"], ["estatuto_atual", "ata_aprovacao"], ["validar_artigos_alterados", "validar_consolidacao"], ["artigo_repetido", "redacao_ambigua", "ata_estatuto_divergentes"]),
    document_type("AUMENTO_CAPITAL_SA", "Aumento de Capital de S/A", "Aumento de capital", "SA", "Ata / Assembleia", "Deliberação de aumento de capital social.", "Registrar novo capital e subscrição.", ["companhia", "capital_atual", "novo_capital", "acoes", "subscritores"], ["boletim_subscricao"], ["boletim_subscricao", "estatuto_social"], ["validar_capital_acoes", "validar_subscricao"], ["capital_divergente", "subscricao_incompleta", "percentuais_inconsistentes"]),
    document_type("REDUCAO_CAPITAL_SA", "Redução de Capital de S/A", "Redução de capital", "SA", "Ata / Assembleia", "Deliberação de redução de capital social.", "Registrar redução conforme deliberação e requisitos aplicáveis.", ["companhia", "capital_atual", "novo_capital", "motivo_reducao"], ["publicacoes", "estatuto_consolidado"], ["estatuto_social", "demonstracoes_financeiras"], ["validar_motivo_reducao", "validar_publicacoes"], ["procedimento_sensivel", "capital_divergente", "prazo_legal_a_conferir"]),
    document_type("TRANSFERENCIA_ACOES", "Transferência de Ações", "Transferência de ações", "SA", "Ata / Assembleia", "Registro operacional de transferência de ações.", "Formalizar transferência e reflexos societários.", ["companhia", "cedente", "cessionario", "acoes", "preco"], ["livro_acoes", "anuencias"], ["documentos_acionistas", "livro_acoes"], ["validar_acoes", "validar_partes"], ["acoes_inconsistentes", "qualificacao_incompleta", "preco_ausente"]),
    document_type("ELEICAO_DIRETORIA", "Eleição de Diretoria", "Eleição de diretoria", "SA", "Ata / Assembleia", "Ato de eleição de diretoria.", "Formalizar cargos, mandato e posse.", ["companhia", "diretores", "cargos", "mandato"], ["termo_posse", "declaracao_desimpedimento"], ["documentos_diretores", "estatuto_social"], ["validar_cargos", "validar_mandato"], ["cargo_inexistente", "mandato_divergente", "desimpedimento_ausente"]),
    document_type("RENUNCIA_DIRETORIA", "Renúncia de Diretoria", "Renúncia de diretoria", "SA", "Ata / Assembleia", "Ato de ciência ou registro de renúncia de diretor.", "Registrar saída de diretor e eventual substituição.", ["companhia", "diretor_renunciante", "data_renuncia"], ["substituto", "carta_renuncia"], ["carta_renuncia", "estatuto_social"], ["validar_renuncia", "validar_substituicao"], ["data_inconsistente", "cargo_vago", "carta_ausente"]),
]
