ISSUE_TYPES = {
    "ORTOGRAFIA", "ACENTUACAO", "CONCORDANCIA", "PONTUACAO", "FORMATACAO",
    "PADRONIZACAO", "REDACAO_FRACA", "COERENCIA_INTERNA", "QUALIFICACAO_SOCIO",
    "QUALIFICACAO_ADMINISTRADOR", "ERRO_GENERO", "ERRO_NUMERACAO",
    "ERRO_REFERENCIA_LEGAL", "CLAUSULA_JURIDICA_SENSIVEL", "INCONSISTENCIA_DOCUMENTAL",
    "DADO_A_CONFERIR", "ASSINATURA_E_FECHAMENTO", "ESTRUTURA_DOCUMENTAL", "OUTRO",
}

SEVERITIES = {"BAIXA", "MEDIA", "ALTA", "CRITICA", "CONFERIR"}

DOCUMENT_STATUS = {
    "UPLOADED", "TEXT_EXTRACTED", "REVIEWING", "REVIEWED", "ANNOTATED_READY",
    "CORRECTED_READY", "FINAL_READY", "ERROR",
}

ISSUE_STATUS = {
    "OPEN", "ACCEPTED", "REJECTED_FALSE_POSITIVE", "NEEDS_HUMAN_CHECK",
    "FIXED", "IGNORED",
}
